repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # must match requirements_dev.txt
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # must match requirements_dev.txt
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # must match requirements_dev.txt
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==23.3.12  # must match requirements_dev.txt
          - flake8-noqa==1.3.1       # must match requirements_dev.txt
