on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: Releases

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: mafia-game-backend
          extra-files: |
            src/whist_backend/__init__.py
            setup.cfg
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      # - name: Set up Python
      #   uses: actions/setup-python@v3
      #   if: ${{ steps.release.outputs.release_created }}
      #   with:
      #     python-version: '3.11'
      # - name: Install pypa/build
      #   if: ${{ steps.release.outputs.release_created }}
      #   run: |
      #     python -m pip install build
      # - name: Build distribution
      #   if: ${{ steps.release.outputs.release_created }}
      #   run: |
      #     python -m build
      # - name: Publish distribution to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   if: ${{ steps.release.outputs.release_created }}
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
